### ISSUE TITLE
How to use this dataset for deep RL

### ISSUE THREAD

**Issue by robert-m-taylor** [wineslab/colosseum-oran-coloran-dataset#2]
Do you have any code/scripts or documentation that describes how to use this dataset to do deep reinforcement learning?   Is there a way to map this dataset into something that resembles a trajectory of <state, action, reward, next-state> rollouts?

**Comment by salvododo** [comment]
Hi, we do have scripts that we use to process the data and convert it into what we could broadly call a trajectory, but there is some IP involved in the scripts and we are not at liberty to share the code. 

However, let me give you some pointers. First, note that data is collected individually for each configuration and there is no dynamic update of actions that would give you a "clean trajectory" with well-defined states. So a possible way to construct a trajectory is to connect each current state (which you could represent as the metrics/parameters listed in the CSV file) with a similar state included in a CSV file produced under another action profile. Let's say that you are in state s_t with action a_t, and you want to move to action a_t+1 and need to extract a new state s_t+1. You can construct that state (or, at least, an approximation of the state) by using some similarity scores so that you can pull a synthetic state from the CSV files. 

It's not straightforward but this can help you in re-creating the temporal relationship between states.

**Comment by hanghoo** [comment]
Hi @gicu8ab2, do you get any progress on this?

**Comment by hanghoo** [comment]
Hi @salvododo, is it possible to form trajectories like <1st-row state, 1st-row action, 1st-row reward, 2nd-row next state>, <2nd-row state, 2nd-row action, 2nd-row reward, 3rd-row next state>, and so on?

**Comment by salvododo** [comment]
Hi, this dataset is primarily tailored at training with tabular data. Since all data is collected using a static policy, you won't have a full MDP with transitions like you want. You only state transitions using the same action. 

Let me know if this responds to your question

**Comment by hanghoo** [comment]
Hi @salvododo, thank you for your response. I have two questions as follows.
1. What about this dataset https://github.com/wineslab/colosseum-oran-commag-dataset
2. Is there any available dataset for DRL training? Thank you.

**Comment by salvododo** [comment]
you can use that to build a state/action transition, yes. See "Dynamic slice resizing" to understand how slicing policies change over time to build a partial MDP

**Comment by hanghoo** [comment]
Hi @salvododo, thank you for sharing the details. It’s great to hear that the Communications Magazine dataset can be used for DRL training.
Since I would like to train the slicing policy instead of scheduling policy, I was wondering how to concatenate the `tr0-tr17`. 
I see the Timestamp difference is around 250ms. Therefore, I don't know how to check the time 0-480s in table of "Dynamic slice resizing".

**Comment by salvododo** [comment]
I would say you can likely select one scheduler (PF should be fine), and then split the CSV files based on slicing policies. 
The data logging resolution is 250ms, and what you see is the unix time timestamp.
Regarding the action change, I suggest you rely on the CSV files to split data based on action transitions (e..g., extract entries with the same slicing profile untile the profile changes). You can use the unix time timestamp to synch the CSV files with the action change in Dynamic slice resizing, but you might find that the unix time stamp might not be perfectly synchronized as logging is much faster then action change and you might have 2 different actions within the same second (because you have 4 entries, each 250ms apart, and the action might change within that second)

**Comment by hanghoo** [comment]
Hi @salvododo, I very much appreciate your detailed explanations. I have another issue. For example, in file `rome_static_close\tr0\exp1\bs1\slices_bs1\1010123456002_metrics.csv` for UE2, the total time period is around 1 min, but I observe the `slice_prb` does not change. Thus, how can I observe 2 different actions within the same second? Or `slice_prb` is not the correct action I should observe? Thank you.

**Comment by salvododo** [comment]
Oh, I see. Sorry but it's been a long time since we published this and I completely forgot. The dataset only includes static policies for each experiment. The dynamic part is performed in testing where we deploy the DRL agent to evaluate how it adapts to changing conditions. Therefore, the dataset does not directly give you state transitions the way you are looking for

**Comment by hanghoo** [comment]
Hi @salvododo, Thank you for the clarification; I understand now. Since we’re also part of the PAWR project (COSMOS project), I’ve posted a similar question via the Colosseum ticket and waiting for response. I’d like to ask if it would be possible to share the available data with us through Colosseum, or if there is any documentation we could follow to generate the data ourselves. Thank you very much for your assistance.

**Comment by salvododo** [comment]
I don't think the ticketing system for Colosseum is the right platform for this. If your goal is to generate datasets and cover state transitions exhaustively, I suggest you follow this https://openrangym.com/tutorials/scope-coloran-o-ran and create a basic xApp that generates deterministic policies in a controlled way so that you can keep track of the state transitions and log them. This would be the most accurate way to generate the data you need on Colosseum (which is now down due to an outage that we are trying to address ASAP)

**Comment by hanghoo** [comment]
Hi @salvododo, thank you very much for the information. Could you please share additional details regarding the deterministic policy to cover state transitions exhaustively? I would greatly appreciate it. Thank you!

**Comment by salvododo** [comment]
What I mean is that you might simply want to generate actions (e.g., new slicing profile) deterministically so that you can cover all state/action transitions you need. You want to at least cover all a_i -> a_i+1 transitions, which means that if you have 3 possible actions (A,B,C), you want to generate actions so that you have A>B, B>C, C>A, A>C, B>A, C>B, A>A, etc... (all combinations)

**Comment by hanghoo** [comment]
Thank you very much for the clarification; I really appreciate it. @salvododo
